import Image from 'next/image';

const teamMembers = [
  { name: "Peer Richelsen", role: "Co-Founder", imageUrl: "/images/TM/peer.jpg" },
  { name: "Bailey Pumfleet", role: "Co-Founder", imageUrl: "/images/TM/bailey.avif" },
  { name: "Alexis Ohanian", role: "Lead Series A", imageUrl: "/images/TM/alex-ohanian.jpeg" },
  { name: "James Joaquin", role: "Lead Series A", imageUrl: "/images/TM/james-joaquin.jpeg" },
  { name: "Joseph Jacks", role: "Lead Seed, Co-Lead Series A", imageUrl: "/images/TM/joseph jacks.jpg" },
  { name: "Tobi Lutke", role: "Series A", imageUrl: "/images/TM/tobi.jpg" },
  { name: "Pomp", role: "Series A", imageUrl: "/images/TM/pomp.jpeg" },
  { name: "Larry", role: "Series A", imageUrl: "/images/TM/larry.jpeg" },
  { name: "Jack Altman", role: "Series A", imageUrl: "/images/TM/jack-altman.jpeg" },
  { name: "Naval Ravikant", role: "Seed", imageUrl: "/images/TM/naval.jpg" },
  { name: "James Beshara", role: "Seed", imageUrl: "/images/TM/james beshara.jpg" },
  { name: "Liu Jiang", role: "Seed", imageUrl: "/images/TM/liu.jpg" },
  { name: "Tod Sacerdoti", role: "Seed", imageUrl: "/images/TM/tod.jpg" },
  { name: "Chad Hurley", role: "Seed", imageUrl: "/images/TM/chad.jpg" },
  { name: "Arjun Sethi", role: "Seed", imageUrl: "/images/TM/arjun.jpg" },
  { name: "Eliot Horowitz", role: "Seed", imageUrl: "/images/TM/eliot.jpg" },
  { name: "Job van der Voort", role: "Seed", imageUrl: "/images/TM/job.jpg" },
  { name: "Balaji S. Srinivasan", role: "Seed", imageUrl: "/images/TM/balajis.jpg" },
  { name: "Beth Turner", role: "Seed", imageUrl: "/images/TM/beth.jpg" },
  { name: "Harini Janakiraman", role: "Seed", imageUrl: "/images/TM/harini.jpg" },
  { name: "Neha Narkhede", role: "Seed", imageUrl: "/images/TM/neha.jpg" },
  { name: "Glenn Solomon", role: "Seed", imageUrl: "/images/TM/glenn.jpg" },
  { name: "Alex Bouaziz", role: "Seed", imageUrl: "/images/TM/alex.jpg" },
  { name: "Guillermo Rauch", role: "Seed", imageUrl: "/images/TM/guillermo.jpg" },
  { name: "Cassidy Williams", role: "Seed", imageUrl: "/images/TM/cassidy.jpg" },
  { name: "Paul Copplestone", role: "Seed", imageUrl: "/images/TM/paul.jpg" },
  { name: "Viet Le", role: "Seed", imageUrl: "/images/TM/viet.jpg" },
  { name: "Nicolai Eddy", role: "Seed", imageUrl: "/images/TM/nico.jpg" },
  { name: "Zach Waterfield", role: "Seed", imageUrl: "/images/TM/zach.jpg" },
  { name: "Regina Gerbeaux", role: "Seed", imageUrl: "/images/TM/regina.jpg" },
  { name: "Ramiro Berrelleza", role: "Seed", imageUrl: "/images/TM/ramiro.jpg" },
  { name: "Angela Santurbano", role: "Seed", imageUrl: "/images/TM/angela.jpg" },
  { name: "Benjamin Fernandes", role: "Seed", imageUrl: "/images/TM/benji.jpg" },
  { name: "Vikram Rajagopalan", role: "Seed", imageUrl: "/images/TM/vikram.jpg" },
  { name: "Julian Weisser", role: "Seed", imageUrl: "/images/TM/julian.jpg" },
  { name: "On Deck", role: "Seed", imageUrl: "/images/TM/ondeck.jpg" },
  { name: "Candice Ammori", role: "Seed", imageUrl: "/images/TM/candice.jpg" },
  { name: "Max Nussenbaum", role: "Seed", imageUrl: "/images/TM/max.jpg" },
  { name: "Art Lapinsch", role: "Seed", imageUrl: "/images/TM/art.jpg" },
  { name: "John K. Harrison", role: "Seed", imageUrl: "/images/TM/john.jpg" },
  { name: "Sven Greulich", role: "Seed", imageUrl: "/images/TM/sven.jpg" },
  { name: "Stefan Schultes-Schnitzlein", role: "Seed", imageUrl: "/images/TM/stefan.jpg" },
  { name: "James Sinka", role: "Seed", imageUrl: "/images/TM/james-sinka.jpg" },
  { name: "Steven Tey", role: "Seed", imageUrl: "/images/TM/steven.jpg" },
  { name: "David J. Phillips", role: "Seed", imageUrl: "/images/TM/david.jpg" },
  { name: "Tyler Willis", role: "Seed", imageUrl: "/images/TM/tyler-willis.jpg" },
  { name: "Travis Kososki", role: "Seed", imageUrl: "/images/TM/travis.jpg" },
  { name: "Brian Vallelunga", role: "Seed", imageUrl: "/images/TM/brian.jpg" },
  { name: "Timo Heinemann", role: "Seed", imageUrl: "/images/TM/timo.jpg" },
  { name: "Mike Mahlkow", role: "Seed", imageUrl: "/images/TM/mike.jpg" },
  { name: "Lester Lee", role: "Seed", imageUrl: "/images/TM/lester.jpg" },
  { name: "Rachel Soper Sanders", role: "Seed", imageUrl: "/images/TM/rachel.jpg" },
  { name: "Jamie Cuffe", role: "Seed", imageUrl: "/images/TM/jc.jpeg" },
  { name: "Michael Tan", role: "Seed", imageUrl: "/images/TM/mi.jpg" },
  { name: "Andreas Klinger", role: "Seed", imageUrl: "/images/TM/an.jpg" },
  { name: "zomars", role: "Contributor", imageUrl: "/images/TM/zo.avif" },
  { name: "PeerRich", role: "Contributor", imageUrl: "/images/TM/peer.jpg" },
  { name: "crowdin-bot", role: "Contributor", imageUrl: "/images/TM/crowdin.avif" },
  { name: "emrysal", role: "Contributor", imageUrl: "/images/TM/emrysal.avif" },
  { name: "hariombalhara", role: "Contributor", imageUrl: "/images/TM/hariom.avif" },
  { name: "sean-brydon", role: "Contributor", imageUrl: "/images/TM/sean.avif" },
  { name: "Udit-takkar", role: "Contributor", imageUrl: "/images/TM/udit.avif" },
  { name: "baileypumfleet", role: "Contributor", imageUrl: "/images/TM/bailey.jpg" },
  { name: "CarinaWolli", role: "Contributor", imageUrl: "/images/TM/carina.avif" },
  { name: "alishaz-polymath", role: "Contributor", imageUrl: "/images/TM/alishnaz.avif" },
  { name: "joeauyeung", role: "Contributor", imageUrl: "/images/TM/joeauyeung.avif" },
  { name: "G3root", role: "Contributor", imageUrl: "/images/TM/g3root.avif" },
  { name: "leog", role: "Contributor", imageUrl: "/images/TM/leog.avif" },
  { name: "agustif", role: "Contributor", imageUrl: "/images/TM/agustif.avif" },
  { name: "alannnc", role: "Contributor", imageUrl: "/images/TM/alannc.avif" },
  { name: "keithwillcode", role: "Contributor", imageUrl: "/images/TM/keithwill.avif" },
  { name: "ThyMinimalDev", role: "Contributor", imageUrl: "/images/TM/thyminimal.avif" },
  { name: "gitstart-calcom", role: "Contributor", imageUrl: "/images/TM/gitstart.avif" },
  { name: "KATT", role: "Contributor", imageUrl: "/images/TM/katt.avif" },
  { name: "JeroenReumkens", role: "Contributor", imageUrl: "/images/TM/jereon.avif" },
  { name: "supalarry", role: "Contributor", imageUrl: "/images/TM/supalarry.avif" },
  { name: "Amit91848", role: "Contributor", imageUrl: "/images/TM/amit.avif" },
  { name: "SomayChauhan", role: "Contributor", imageUrl: "/images/TM/somay.avif" },
  { name: "gitstart", role: "Contributor", imageUrl: "/images/TM/gitstart 2.avif" },
  { name: "femyeda", role: "Contributor", imageUrl: "/images/TM/femyeda.avif" },
  { name: "mihaiac195", role: "Contributor", imageUrl: "/images/TM/mihaic.avif" },
  { name: "Malte-D", role: "Contributor", imageUrl: "/images/TM/malte d.avif" },
  { name: "roae", role: "Contributor", imageUrl: "/images/TM/roae.avif" },
  { name: "exception", role: "Contributor", imageUrl: "/images/TM/exception.avif" },
  { name: "anikdhabal", role: "Contributor", imageUrl: "/images/TM/anikdhabal.avif" },
  { name: "DmytroHryshyn", role: "Contributor", imageUrl: "/images/TM/dmytro.avif" },
  { name: "Ryukemeister", role: "Contributor", imageUrl: "/images/TM/ryuke.avif" },
  { name: "p6l-richard", role: "Contributor", imageUrl: "/images/TM/p6i.avif" },
  { name: "denik1981", role: "Contributor", imageUrl: "/images/TM/denik.avif" },
  { name: "hbjORbj", role: "Contributor", imageUrl: "/images/TM/hbj.avif" },
  { name: "ujwalkumar1995", role: "Contributor", imageUrl: "/images/TM/ujwal.avif" },
  { name: "joe-shajan", role: "Contributor", imageUrl: "/images/TM/joe shajan.avif" },
  { name: "MehulZR", role: "Contributor", imageUrl: "/images/TM/mehul.avif" },
  { name: "grzpab", role: "Contributor", imageUrl: "/images/TM/grzpab.avif" },
  { name: "afzalsayed96", role: "Contributor", imageUrl: "/images/TM/afzal.avif" },
  { name: "harshinghatz", role: "Contributor", imageUrl: "/images/TM/harsh.avif" },
  { name: "Pradumn27", role: "Contributor", imageUrl: "/images/TM/pradumn.avif" },
  { name: "miguelnietoa", role: "Contributor", imageUrl: "/images/TM/miguel.avif" },
  { name: "shivamklr", role: "Contributor", imageUrl: "/images/TM/shivamklr.avif" },
  { name: "jamiepine", role: "Contributor", imageUrl: "/images/TM/jamie.avif" },
  { name: "JaideepGuntupalli", role: "Contributor", imageUrl: "/images/TM/jaideep.avif" },
  { name: "Siddharth-2382", role: "Contributor", imageUrl: "/images/TM/sidharth.avif" },
  { name: "nicktrn", role: "Contributor", imageUrl: "/images/TM/nicktrn.avif" },
  { name: "riddhesh-mahajan", role: "Contributor", imageUrl: "/images/TM/ridhesh.avif" },
  { name: "asadath1395", role: "Contributor", imageUrl: "/images/TM/asadath.avif" },
  { name: "DexterStorey", role: "Contributor", imageUrl: "/images/TM/dexter.avif" },
  { name: "phishy", role: "Contributor", imageUrl: "/images/TM/phishy.avif" },
  { name: "anorig", role: "Contributor", imageUrl: "/images/TM/anonrig.avif" },
  { name: "montocoder", role: "Contributor", imageUrl: "/images/TM/montocoder.avif" },
  { name: "Shaik-Sirajuddin", role: "Contributor", imageUrl: "/images/TM/shaik.avif" },
  { name: "rene-mueller", role: "Contributor", imageUrl: "/images/TM/rene.avif" },
  { name: "rkeddy99", role: "Contributor", imageUrl: "/images/TM/rkreddy.avif" },
  { name: "Dhoni77", role: "Contributor", imageUrl: "/images/TM/dhoni.avif" },
  { name: "podviaznikov", role: "Contributor", imageUrl: "/images/TM/podvia.avif" },
  { name: "Hybes", role: "Contributor", imageUrl: "/images/TM/hybes.avif" },
  { name: "ciaranha", role: "Contributor", imageUrl: "/images/TM/ciaranha.avif" },
  { name: "om-ray", role: "Contributor", imageUrl: "/images/TM/omray.avif" },
  { name: "kartlka", role: "Contributor", imageUrl: "/images/TM/kart1ka.avif" },
  { name: "buschco", role: "Contributor", imageUrl: "/images/TM/buschco.avif" },
  { name: "hussamkhatib", role: "Contributor", imageUrl: "/images/TM/hussam.avif" },
  { name: "bytesbuffer", role: "Contributor", imageUrl: "/images/TM/bytesbuffer.avif" },
  { name: "deepakprabhakara", role: "Contributor", imageUrl: "/images/TM/deepak.avif" },
  { name: "vklimontovich", role: "Contributor", imageUrl: "/images/TM/vklimon.avif" },
  { name: "jemiluv8", role: "Contributor", imageUrl: "/images/TM/jemiluv.avif" },
  { name: "juliandsg0222", role: "Contributor", imageUrl: "/images/TM/juliandsg.avif" },
  { name: "vijayraghav-io", role: "Contributor", imageUrl: "/images/TM/vijay.avif" },
  { name: "ShaneMaglangit", role: "Contributor", imageUrl: "/images/TM/shane.avif" },
  { name: "r4zendeV", role: "Contributor", imageUrl: "/images/TM/r4z.avif" },
  { name: "saideepesh000", role: "Contributor", imageUrl: "/images/TM/saideep.avif" },
  { name: "rjackson", role: "Contributor", imageUrl: "/images/TM/rjack.avif" },
  { name: "natelinedev", role: "Contributor", imageUrl: "/images/TM/natelindev.avif" },
  { name: "Mythie", role: "Contributor", imageUrl: "/images/TM/mythie.avif" },
  { name: "krunalshahcodes", role: "Contributor", imageUrl: "/images/TM/krunal.avif" },
  { name: "juliusmarminge", role: "Contributor", imageUrl: "/images/TM/julius.avif" },
  { name: "Hashen110", role: "Contributor", imageUrl: "/images/TM/hashen.avif" },
  { name: "esau-morais", role: "Contributor", imageUrl: "/images/TM/esau.avif" },
  { name: "Chiranjev-droid", role: "Contributor", imageUrl: "/images/TM/chiranjeev.avif" },
  { name: "ikadix", role: "Contributor", imageUrl: "/images/TM/ikadix.avif" },
  { name: "moherfaoui", role: "Contributor", imageUrl: "/images/TM/mocher.avif" },
  { name: "ologbonowiwi", role: "Contributor", imageUrl: "/images/TM/olog.avif" },
  { name: "rymaj", role: "Contributor", imageUrl: "/images/TM/rymaju.avif" },
  { name: "RushikeshGandhmal", role: "Contributor", imageUrl: "/images/TM/rushikesh.avif" },
  { name: "iamr-kumar", role: "Contributor", imageUrl: "/images/TM/iamr.avif" },
  { name: "pateldivyesh1323", role: "Contributor", imageUrl: "/images/TM/patel.avif" },
  { name: "manpoffc", role: "Contributor", imageUrl: "/images/TM/manpoffc.avif" },
  { name: "devkiran", role: "Contributor", imageUrl: "/images/TM/devkiran.avif" },
  { name: "hichemfantar", role: "Contributor", imageUrl: "/images/TM/hichem.avif" },
  { name: "ee07b570", role: "Contributor", imageUrl: "/images/TM/ee07.avif" },
  { name: "abhijeetsingh-22", role: "Contributor", imageUrl: "/images/TM/abhijeet.avif" },
  { name: "AyushMainali123", role: "Contributor", imageUrl: "/images/TM/ayush.avif" },
  { name: "Raghul18", role: "Contributor", imageUrl: "/images/TM/raghul.avif" }
];

export default function TeamSection() {
  return (
    <div className="bg-white py-12 px-4">
      <div className="max-w-7xl mx-auto">
        <h2 className="text-center text-3xl font-bold mb-10">You are in good company</h2>
        <p className="text-xl mb-10 text-center text-gray-500">Meet the team members, early adopters, investors and community members</p>
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-8">
          {teamMembers.map(member => (
            <div key={member.name} className="text-center space-y-2 transition duration-300 ease-in-out hover:scale-105">
              <div className="w-24 h-24 mx-auto rounded-full overflow-hidden border-2 border-gray-300 hover:border-gray-500">
                <Image src={member.imageUrl} alt={member.name} width={96} height={96} layout="responsive" className="hover:scale-110" />
              </div>
              <div>
                <h3 className="text-sm font-medium">{member.name}</h3>
                <p className="text-xs text-gray-500">{member.role}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}